2020-06-06 13:37:29,169 INFO: Microblog startup [in /home/daomaster/Desktop/venv/miguel_flask/app/__init__.py:43]
2020-06-06 13:38:07,712 ERROR: Exception on /user/susan [GET] [in /home/daomaster/Desktop/venv/venv/lib/python3.7/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/home/daomaster/Desktop/venv/venv/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/daomaster/Desktop/venv/venv/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/daomaster/Desktop/venv/venv/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/daomaster/Desktop/venv/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/daomaster/Desktop/venv/venv/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/daomaster/Desktop/venv/venv/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/daomaster/Desktop/venv/venv/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/daomaster/Desktop/venv/miguel_flask/app/routes.py", line 44, in user
    return render_template('user.html', user=user, posts=posts, form=form)
  File "/home/daomaster/Desktop/venv/venv/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/daomaster/Desktop/venv/venv/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/daomaster/Desktop/venv/venv/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/daomaster/Desktop/venv/venv/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/daomaster/Desktop/venv/venv/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/daomaster/Desktop/venv/miguel_flask/app/templates/user.html", line 1, in top-level template code
    {% extends "base.html" %} {% block content %}
  File "/home/daomaster/Desktop/venv/miguel_flask/app/templates/base.html", line 28, in top-level template code
    {% endif %} {% endwith %} {% block content %}{% endblock %}
  File "/home/daomaster/Desktop/venv/miguel_flask/app/templates/user.html", line 20, in block "content"
    <form action="{{url_for(follow,username=user.username)}}" method="POST">
  File "/home/daomaster/Desktop/venv/venv/lib/python3.7/site-packages/flask/helpers.py", line 318, in url_for
    if endpoint[:1] == ".":
jinja2.exceptions.UndefinedError: 'follow' is undefined
2020-06-06 13:38:56,098 ERROR: Exception on /user/susan [GET] [in /home/daomaster/Desktop/venv/venv/lib/python3.7/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/home/daomaster/Desktop/venv/venv/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/daomaster/Desktop/venv/venv/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/daomaster/Desktop/venv/venv/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/daomaster/Desktop/venv/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/daomaster/Desktop/venv/venv/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/daomaster/Desktop/venv/venv/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/daomaster/Desktop/venv/venv/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/daomaster/Desktop/venv/miguel_flask/app/routes.py", line 44, in user
    return render_template('user.html', user=user, posts=posts, form=form)
  File "/home/daomaster/Desktop/venv/venv/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/daomaster/Desktop/venv/venv/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/daomaster/Desktop/venv/venv/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/daomaster/Desktop/venv/venv/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/daomaster/Desktop/venv/venv/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/daomaster/Desktop/venv/miguel_flask/app/templates/user.html", line 1, in top-level template code
    {% extends "base.html" %} {% block content %}
  File "/home/daomaster/Desktop/venv/miguel_flask/app/templates/base.html", line 28, in top-level template code
    {% endif %} {% endwith %} {% block content %}{% endblock %}
  File "/home/daomaster/Desktop/venv/miguel_flask/app/templates/user.html", line 20, in block "content"
    <form action="{{url_for('follow',username=user.username)}}" method="POST">
  File "/home/daomaster/Desktop/venv/venv/lib/python3.7/site-packages/flask/helpers.py", line 318, in url_for
    if endpoint[:1] == ".":
jinja2.exceptions.UndefinedError: 'follow' is undefined
2020-06-06 13:38:56,998 ERROR: Exception on /user/susan [GET] [in /home/daomaster/Desktop/venv/venv/lib/python3.7/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/home/daomaster/Desktop/venv/venv/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/daomaster/Desktop/venv/venv/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/daomaster/Desktop/venv/venv/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/daomaster/Desktop/venv/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/daomaster/Desktop/venv/venv/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/daomaster/Desktop/venv/venv/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/daomaster/Desktop/venv/venv/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/daomaster/Desktop/venv/miguel_flask/app/routes.py", line 44, in user
    return render_template('user.html', user=user, posts=posts, form=form)
  File "/home/daomaster/Desktop/venv/venv/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/daomaster/Desktop/venv/venv/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/daomaster/Desktop/venv/venv/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/daomaster/Desktop/venv/venv/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/daomaster/Desktop/venv/venv/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/daomaster/Desktop/venv/miguel_flask/app/templates/user.html", line 1, in top-level template code
    {% extends "base.html" %} {% block content %}
  File "/home/daomaster/Desktop/venv/miguel_flask/app/templates/base.html", line 28, in top-level template code
    {% endif %} {% endwith %} {% block content %}{% endblock %}
  File "/home/daomaster/Desktop/venv/miguel_flask/app/templates/user.html", line 20, in block "content"
    <form action="{{url_for('follow',username=user.username)}}" method="POST">
  File "/home/daomaster/Desktop/venv/venv/lib/python3.7/site-packages/flask/helpers.py", line 318, in url_for
    if endpoint[:1] == ".":
jinja2.exceptions.UndefinedError: 'follow' is undefined
