2020-06-10 20:53:59,988 ERROR: Exception on /reset_password_request [GET] [in /home/daomaster/Desktop/venv/venv/lib/python3.7/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/home/daomaster/Desktop/venv/venv/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/daomaster/Desktop/venv/venv/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/daomaster/Desktop/venv/venv/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/daomaster/Desktop/venv/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/daomaster/Desktop/venv/venv/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/daomaster/Desktop/venv/venv/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/daomaster/Desktop/venv/miguel_flask/app/routes.py", line 175, in reset_password_request
    title='Reset Password', form=form)
  File "/home/daomaster/Desktop/venv/venv/lib/python3.7/site-packages/flask/templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/daomaster/Desktop/venv/venv/lib/python3.7/site-packages/jinja2/environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/daomaster/Desktop/venv/venv/lib/python3.7/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/daomaster/Desktop/venv/venv/lib/python3.7/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/daomaster/Desktop/venv/venv/lib/python3.7/site-packages/jinja2/loaders.py", line 127, in load
    code = environment.compile(source, name, filename)
  File "/home/daomaster/Desktop/venv/venv/lib/python3.7/site-packages/jinja2/environment.py", line 638, in compile
    self.handle_exception(source=source_hint)
  File "/home/daomaster/Desktop/venv/venv/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/daomaster/Desktop/venv/venv/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/daomaster/Desktop/venv/miguel_flask/app/templates/reset_password_request.html", line 9, in template
    {% endblock }
jinja2.exceptions.TemplateSyntaxError: unexpected '}'
2020-06-10 20:54:06,718 INFO: Microblog startup [in /home/daomaster/Desktop/venv/miguel_flask/app/__init__.py:51]
2020-06-10 20:54:07,800 ERROR: Exception on /reset_password_request [GET] [in /home/daomaster/Desktop/venv/venv/lib/python3.7/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/home/daomaster/Desktop/venv/venv/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/daomaster/Desktop/venv/venv/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/daomaster/Desktop/venv/venv/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/daomaster/Desktop/venv/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/daomaster/Desktop/venv/venv/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/daomaster/Desktop/venv/venv/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/daomaster/Desktop/venv/miguel_flask/app/routes.py", line 175, in reset_password_request
    title='Reset Password', form=form)
  File "/home/daomaster/Desktop/venv/venv/lib/python3.7/site-packages/flask/templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/daomaster/Desktop/venv/venv/lib/python3.7/site-packages/jinja2/environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/daomaster/Desktop/venv/venv/lib/python3.7/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/daomaster/Desktop/venv/venv/lib/python3.7/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/daomaster/Desktop/venv/venv/lib/python3.7/site-packages/jinja2/loaders.py", line 127, in load
    code = environment.compile(source, name, filename)
  File "/home/daomaster/Desktop/venv/venv/lib/python3.7/site-packages/jinja2/environment.py", line 638, in compile
    self.handle_exception(source=source_hint)
  File "/home/daomaster/Desktop/venv/venv/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/daomaster/Desktop/venv/venv/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/daomaster/Desktop/venv/miguel_flask/app/templates/reset_password_request.html", line 9, in template
    {% endblock }
jinja2.exceptions.TemplateSyntaxError: unexpected '}'
2020-06-10 20:54:26,943 INFO: Microblog startup [in /home/daomaster/Desktop/venv/miguel_flask/app/__init__.py:51]
2020-06-10 20:54:28,489 ERROR: Exception on /reset_password_request [GET] [in /home/daomaster/Desktop/venv/venv/lib/python3.7/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/home/daomaster/Desktop/venv/venv/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/daomaster/Desktop/venv/venv/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/daomaster/Desktop/venv/venv/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/daomaster/Desktop/venv/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/daomaster/Desktop/venv/venv/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/daomaster/Desktop/venv/venv/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/daomaster/Desktop/venv/miguel_flask/app/routes.py", line 175, in reset_password_request
    title='Reset Password', form=form)
  File "/home/daomaster/Desktop/venv/venv/lib/python3.7/site-packages/flask/templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/daomaster/Desktop/venv/venv/lib/python3.7/site-packages/jinja2/environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/daomaster/Desktop/venv/venv/lib/python3.7/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/daomaster/Desktop/venv/venv/lib/python3.7/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/daomaster/Desktop/venv/venv/lib/python3.7/site-packages/jinja2/loaders.py", line 127, in load
    code = environment.compile(source, name, filename)
  File "/home/daomaster/Desktop/venv/venv/lib/python3.7/site-packages/jinja2/environment.py", line 638, in compile
    self.handle_exception(source=source_hint)
  File "/home/daomaster/Desktop/venv/venv/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/daomaster/Desktop/venv/venv/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/daomaster/Desktop/venv/miguel_flask/app/templates/reset_password_request.html", line 9, in template
    {% endblock }
jinja2.exceptions.TemplateSyntaxError: unexpected '}'
2020-06-10 20:55:07,255 INFO: Microblog startup [in /home/daomaster/Desktop/venv/miguel_flask/app/__init__.py:51]
